/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeStudioRouteImport } from './routes/resume-studio'
import { Route as JobDiscoveryRouteImport } from './routes/job-discovery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyResearchRouteImport } from './routes/company-research'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeStudioRoute = ResumeStudioRouteImport.update({
  id: '/resume-studio',
  path: '/resume-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDiscoveryRoute = JobDiscoveryRouteImport.update({
  id: '/job-discovery',
  path: '/job-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyResearchRoute = CompanyResearchRouteImport.update({
  id: '/company-research',
  path: '/company-research',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/company-research': typeof CompanyResearchRoute
  '/dashboard': typeof DashboardRoute
  '/job-discovery': typeof JobDiscoveryRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/company-research': typeof CompanyResearchRoute
  '/dashboard': typeof DashboardRoute
  '/job-discovery': typeof JobDiscoveryRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/company-research': typeof CompanyResearchRoute
  '/dashboard': typeof DashboardRoute
  '/job-discovery': typeof JobDiscoveryRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/company-research'
    | '/dashboard'
    | '/job-discovery'
    | '/resume-studio'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/company-research'
    | '/dashboard'
    | '/job-discovery'
    | '/resume-studio'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/company-research'
    | '/dashboard'
    | '/job-discovery'
    | '/resume-studio'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  CompanyResearchRoute: typeof CompanyResearchRoute
  DashboardRoute: typeof DashboardRoute
  JobDiscoveryRoute: typeof JobDiscoveryRoute
  ResumeStudioRoute: typeof ResumeStudioRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-studio': {
      id: '/resume-studio'
      path: '/resume-studio'
      fullPath: '/resume-studio'
      preLoaderRoute: typeof ResumeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-discovery': {
      id: '/job-discovery'
      path: '/job-discovery'
      fullPath: '/job-discovery'
      preLoaderRoute: typeof JobDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-research': {
      id: '/company-research'
      path: '/company-research'
      fullPath: '/company-research'
      preLoaderRoute: typeof CompanyResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  CompanyResearchRoute: CompanyResearchRoute,
  DashboardRoute: DashboardRoute,
  JobDiscoveryRoute: JobDiscoveryRoute,
  ResumeStudioRoute: ResumeStudioRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
